AWSTemplateFormatVersion: "2010-09-09"
Resources: 
  SQSQueue: 
    Type: AWS::SQS::Queue
    Properties: 
      RedrivePolicy: 
        deadLetterTargetArn: !GetAtt DeadLetterQueue.Arn
        maxReceiveCount: 5

Outputs:
  SQSQueueArn:
    Value: !GetAtt SQSQueue.Arn